labels: [idea]
body:
  - type: markdown
    attributes:
      value: |
        ## アイデア
        
        プロジェクトの改善案や新しいアイデアを共有する場です。
        
        以下の内容を含めると良いでしょう：
        - 💡 アイデアの概要
        - 🎯 解決したい課題
        - 📝 実現方法の提案
        - 🤔 検討すべき点
