labels: [question]
body:
  - type: markdown
    attributes:
      value: |
        ## Q&A
        
        使い方や技術的な質問をする場です。
        
        質問する前に：
        - README.mdとドキュメントを確認しましたか？
        - 既存のIssueやDiscussionを検索しましたか？
        
        質問する際は：
        - ✅ 何をしようとしているか
        - ❓ どこでつまづいているか
        - 💻 エラーメッセージや設定ファイル（あれば）
        
        を含めると回答を得やすくなります。
